# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Michael Tritschler
tagline:          Pages
url:              http://michaeltritschler.de
paginate:         1
baseurl:          /
author:
  name:           Michael Tritschler
  url:            https://twitter.com/michaeltri
  email:          -

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/michaeltri
