# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            MT
tagline:          michael tritschler
url:              http://michaeltritschler.de
paginate:         3
baseurl:          /
author:
  name:           Michael Tritschler
  url:            https://twitter.com/michaeltri
  email:          mt@mail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/michaeltri
